site_name: Roberts Lab Virtual Open House
theme:
  name: readthedocs

    #
    # # Light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: green
    #   accent: green
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    #
    # # Dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: pink
    #   accent: pink
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

repo_url:

nav:
   - Welcome!: 'index.md'
   - Where the Magic Happens - Visit a Shellfish Hatchery!: 'Hatchery.md'
   - Oyster Circle of Life: 'oysterlifecycle.md'
   - Let's Play With Data! (Part 1): 'dataPart1.md'
   - Let's Play With Data! (Part 2): 'dataPart2.md'
   - What Other Data Can We Collect?: 'DNA_Isolation.md'
   - Thanks for coming!: 'Thanks.md'
