site_name: Roberts Lab Virtual Open House
theme:
  name: material
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
repo_url: https://github.com/RobertsLab/Open-House-2021/
nav:
   - Welcom: 'index.md'
   - Hatchery Tour: 'Hatchery.md'
   - Sablefish Release: 'Sablefish.md'
