site_name: Roberts Lab Virtual Open House
theme:
  name: readthedocs

    #
    # # Light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: green
    #   accent: green
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    #
    # # Dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: pink
    #   accent: pink
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

repo_url:

nav:
   - Welcome!: 'index.md'
   - Hatchery Tour - Where the Magic Happens: 'Hatchery.md'
   - Oyster Circle of Life: 'oysterlifecycle.md'
   - Let's play with data!: 'Ostrea.md'
   - How can we get data?: 'DNA_Isolation.md'
   - Thanks for coming!: Thanks.md
